# Generated by Django 4.2 on 2023-09-18 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BECL_Login', '0001_initial'),
        ('BECL_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('dependencia', models.CharField(max_length=150)),
                ('inicio', models.CharField(max_length=20)),
                ('final', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('cantidad_personas', models.IntegerField()),
                ('tipo', models.CharField(max_length=10)),
                ('encargados', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('url_formato', models.CharField(blank=True, max_length=150)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_event', to='BECL_Admin.estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_event', to='BECL_Login.usuarios')),
            ],
        ),
    ]
