# Generated by Django 4.2 on 2023-05-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BECL_PDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_p',
            name='entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events_p',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
