# Generated by Django 4.2 on 2023-06-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BECL_PDB', '0002_events_p_entrega_events_p_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_p',
            name='observaciones',
            field=models.TextField(blank=True, default=None),
        ),
    ]
