# Generated by Django 4.2 on 2023-06-05 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BECL_Admin', '0001_initial'),
        ('BECL_Login', '0004_merge_20230413_1633'),
        ('BECL_PDB', '0004_alter_events_db_id_alter_events_p_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=50)),
                ('fecha_registro', models.CharField(max_length=50)),
                ('dependencia', models.CharField(max_length=150)),
                ('inicio', models.CharField(max_length=20)),
                ('final', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('cantidad_personas', models.IntegerField()),
                ('tipo', models.CharField(max_length=10)),
                ('encargados', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('url_formato', models.CharField(max_length=150)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_event', to='BECL_Admin.estado')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_event', to='BECL_Login.usuarios')),
            ],
        ),
        migrations.RemoveField(
            model_name='events_p',
            name='codigo_user',
        ),
        migrations.DeleteModel(
            name='Events_DB',
        ),
        migrations.DeleteModel(
            name='Events_P',
        ),
    ]
