# Generated by Django 4.2 on 2023-06-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BECL_PDB', '0005_eventos_remove_events_p_codigo_user_delete_events_db_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='id_estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
