# Generated by Django 4.2 on 2023-06-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BECL_PDB', '0006_rename_id_estado_eventos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='url_formato',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
