# Generated by Django 4.2 on 2023-06-07 20:51

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BECL_PDB', '0007_alter_eventos_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='encargados',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]), size=None),
        ),
    ]
