# Generated by Django 4.2 on 2023-06-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('por_revisar', models.BooleanField(default=False)),
                ('aceptado', models.BooleanField(default=False)),
                ('rechazado', models.BooleanField(default=False)),
            ],
        ),
    ]
