# Generated by Django 4.2 on 2023-06-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BECL_Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='aceptado',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='por_revisar',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='rechazado',
        ),
        migrations.AddField(
            model_name='estado',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
