# Generated by Django 4.2 on 2023-04-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BECL_Login', '0002_usuarios_delete_usuario'),
        ('BECL_Login', '0003_auto_20230413_1632'),
    ]

    operations = [
    ]
